#marca
#Motor 
#color 

class coche:

    #constructor
    def __init__(self, marca: str, motor: int, color ):
        self.marca = marca
        self.motor = motor
        self.color = color
        self.velocidad = 0
 
def arrancar(self):
    print("el coche esta arrancando")

def frenar (self):
    print("el coche esta frenando")

auto1 = coche ("ford", 4700, "blanco"  )


coche.arrancar(25)
print("velocidad")

        


    